# Generated by Django 5.1.4 on 2025-03-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('templatename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'templates',
            },
        ),
    ]
