# Generated by Django 5.1.4 on 2025-01-05 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='orgnization_name',
            new_name='organization_name',
        ),
    ]
