# Generated by Django 5.1.4 on 2025-03-19 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='templates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commons.templates'),
        ),
    ]
