# Generated by Django 5.1.4 on 2025-02-17 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_rename_orgnization_name_organization_organization_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickBillDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=256, null=True)),
                ('customer_addr', models.CharField(blank=True, max_length=256, null=True)),
                ('customer_email', models.CharField(blank=True, max_length=256, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=256, null=True)),
                ('bill_id', models.CharField(blank=True, max_length=256, null=True)),
                ('bill_total', models.CharField(blank=True, max_length=256, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_biller', to=settings.AUTH_USER_MODEL)),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
